### ISSUE TITLE
Unsaved literature note gets repeating headers on subsequent opens

### ISSUE THREAD

**Issue by goderich** [joostkremers/ebib#182] opened 2020-09-22 07:48 UTC
Hello again!

When I do the following:

1. In the index mode, navigate to an entry that does not have a literature note.
2. Press N to create a new literature note.
3. Close the note without saving.
4. Press N again.

The autogenerated header is repeated twice. If I close the buffer and open the note again, the header will be repeated three times, etc.

This happens only when the note is unsaved. I haven't had the time to look into the code yet, but judging by the behaviour, the note-creating function appends the header to a global variable every time a new note is created.

**Comment by joostkremers** [comment] 2020-09-22 12:51
I assume you save each note to a separate file? When you create or open a note with `N`, Ebib checks if the current entry has a note already. If not, a new buffer is created and the header is inserted.

The problem is that if you save each note to a separate file, Ebib basically just checks if the relevant file exists in order to determine if the entry has a note already. In the case you describe, however, the note buffer already exists but the file does not. When you press `N` the second time, Ebib finds the buffer but not the file, so it thinks the note is new and duly inserts the header again.

I could add a check for the buffer itself to the mechanism. That would improve things, but is also not entirely reliable, because the buffer may exist but without the header. I could check whether the header is present in the buffer, but there are all sorts of scenarios one could come up with in which that fails as well.

I'll think about it a bit and see what I can do about it.

**Comment by goderich** [comment] 2020-09-23 01:24
That's weird, because I'm using `kill-this-buffer` to close/kill the unsaved note. How does the buffer still exist if I've already killed it?

I am indeed saving each note to a separate file.

**Comment by joostkremers** [comment] 2020-09-23 09:35
Are you sure you're really killing the buffer? I'm not able to reproduce the problem (using [emacs-sandbox.sh](https://github.com/alphapapa/emacs-sandbox.sh), so my own config doesn't get in the way). If I kill the buffer, it's really gone; pressing `N` a second time doesn't give me a double header.

When you kill the buffer without saving the note, you should be prompted if you really want to kill the buffer, because it's visiting a file that hasn't been saved. If you're not prompted, I suspect you're not really killing the buffer, just the window showing the buffer.

The header isn't stored in some global variable, it's created as a string when you create a new note and then inserted in the buffer. After the relevant function (`ebib--notes-create-new-note`) has run, any variable referring to the string is gone, so the only place the header survives is in the buffer.

**Comment by goderich** [comment] 2020-09-24 01:27
You were right and I was wrong; sorry for misleading you.

I misremembered the key combo / function that I've been using to kill those buffers. What *actually* gives me the bug is `evil-quit`, whereas `kill-this-buffer` prompts me first, and if I say yes, the header does not reappear a second time.

I'm assuming you don't use evil. I believe in my case it runs the `delete-frame` function (I open literature notes in a separate frame), but it might behave the same way with `delete-window`.

So yes, the behaviour only happens with an unsaved buffer. As a matter of fact, you don't even have to close it. Just pressing N with a buffer already in place inserts an extra header.

**Comment by joostkremers** [comment] 2020-09-24 10:49
> You were right and I was wrong; sorry for misleading you.

Hey, no worries. It's still a bug that I'd like to get fixed.

> So yes, the behaviour only happens with an unsaved buffer. As a matter of fact, you don't even have to close it. Just pressing N again on an entry with an unsaved buffer already open, inserts an extra header in the buffer.

Yes, that would make sense. It shouldn't matter if the window is deleted or not.

I changed this issue from "minor bug" to "bug", because when I looked at the code more closely, I noticed that there's actually a bigger problem than what I initially surmised. When the user hits `N`, the way Ebib checks whether there's an existing note isn't correct. I need to delve into the code more thoroughly, though, to make sure I understand it properly and fix it in a way that doesn't break anything else. (Yes, I know, I wrote that code myself, but that was oh so long ago... :weary:)

**Comment by joostkremers** [comment] 2020-09-26 23:01
I just pushed a commit that should fix this issue. It turned out the problem wasn't exactly where I initially thought it was and it wasn't as complex as I feared when I first took a closer look.

Do let me know if you run into any problems and thank you for reporting this issue.

**Comment by joostkremers** [comment] 2020-09-27 20:41
I made a small change to the way I fixed this issue, so the next update might theoretically cause some breakage that wasn't there after the first fix. There shouldn't be, and I don't really expect any, but you never know.

I'll close this issue now, but if any problem turns up, just let me know.

**Closed by joostkremers** 2020-09-27 20:41 UTC
Labels: Bug

**Comment by goderich** [comment] 2020-09-29 03:01
Just tested it, seems to be working perfectly fine, thank you!
