### ISSUE TITLE
Compilation and launch errors

### ISSUE THREAD

**Issue by rnkn** [joostkremers/ebib#61] opened 2014-12-27 09:18 UTC
I get the following when installing the 2.1.0 package:
~~~
ebib.el:1106:16:Error: `add-to-list' can't use lexical var `entry-alist'; use
    `push' or `cl-pushnew'
ebib.el:1660:1:Error: Wrong number of arguments: ((t) (prompt-string insert-fn)
~~~
Then `M-x ebib` returns an error, with:
~~~
Eager macro-expansion failure: (wrong-number-of-arguments ((t) (prompt-string insert-fn) "Export data to a file.
PROMPT-STRING is the string that is used to ask for the filename
to export to. INSERT-FN must insert the data to be exported into
the current buffer: it is called within a `with-temp-buffer',
whose contents is appended to the file the user enters." (let ((filename (make-symbol "filename"))) (list (quote let) (quote ((insert-default-directory (not ebib--export-filename)))) (list (quote ebib--ifstring) (list filename (cons (quote read-file-name) (cons prompt-string (quote ("~/" nil nil ebib--export-filename))))) (list (quote with-temp-buffer) (list (quote funcall) insert-fn) (list (quote append-to-file) (quote (point-min)) (quote (point-max)) filename) (list (quote setq) (quote ebib--export-filename) filename)))))) 3)
Eager macro-expansion failure: (wrong-type-argument sequencep if)
load-with-code-conversion: Invalid read syntax: ")"
~~~

**Comment by joostkremers** [comment] 2015-01-01 13:24
Ok, I found the cause of the error and pushed a fix. Everything should be working again, I hope. Let me know if you still run into problems.

I'll have to have a serious talk with the QA department for sending out an update that apparently wasn't tested...

**Closed** 2015-01-02 09:28 UTC

**Comment by rnkn** [comment] 2015-01-07 01:24
Can you tag a 2.1.1 release for MELPA-stable please?

**Comment by joostkremers** [comment] 2015-01-07 08:05
Sorry, I had created the tag but forgot to run `git push --tags`...
