### ISSUE TITLE
Invalid function: with-ivy-window

### ISSUE THREAD

**Issue by mgcyung** [joostkremers/ebib#127] opened 2019-01-28 09:59 UTC
When invoke ebib-insert-citation in orgmode, there is a error
"with-ivy-window", though the citation is inserted.

**Comment by joostkremers** [comment] 2019-01-29 20:33
What exactly is the error you get? `with-ivy-window` is used in the function `ebib-ivy-insert-citation`, which only gets called if `ivy` is installed, in which case `with-ivy-window` should not result in an error...

**Comment by mgcyung** [comment] 2019-01-30 13:51
> What exactly is the error you get? `with-ivy-window` is used in the function `ebib-ivy-insert-citation`, which only gets called if `ivy` is installed, in which case `with-ivy-window` should not result in an error...

Sorry for the incompletion of the error message. The error is
"invalid-function with-ivy-window".

The bibtex file contains only one entry
``` bibtex
@Article{Strobel_1997,
	author = {Strobel, Stefan and Elling, Volker},
	title = {GNU Emacs},
	year = 1997,
	pages = {347–384},
	doi = {10.1007/978-1-4612-1856-2_13},
	url = {http://dx.doi.org/10.1007/978-1-4612-1856-2_13},
	isbn = 9781461218562,
	journal = {Linux},
	publisher = {Springer New York}
}
```
And the backtrace is as follows
```
Debugger entered--Lisp error: (invalid-function with-ivy-window)
  with-ivy-window(nil 49 nil 69)
  #f(compiled-function (item) #<bytecode 0x22ca6a5>)(#("Strobel, Stefan and Elling, Volker (1997) «GNU Emacs»" 0 1 (ebib-key "Strobel_1997" ebib-db #s(ebib--db-struct #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("Strobel_1997" (("publisher" . "{Springer New York}") ("journal" . "{Linux}") ("isbn" . "9781461218562") ("url" . "{http://dx.doi.org/10.1007/978-1-4612-1856-2_13}") ("doi" . "{10.1007/978-1-4612-1856-2_13}") ("pages" . "{347–384}") ("year" . "1997") ("title" . "{GNU Emacs}") ("author" . "{Strobel, Stefan and Elling, Volker}") ("=type=" . "Article") ("=key=" . "Strobel_1997")) ...)) nil nil nil nil nil #<buffer  1:test.bib> "Strobel_1997" nil nil nil "/home/magic/mgc/code/org/ebib/test.bib" (23633 43760 217328 777000) nil t) ebib--xref nil) 1 36 (ebib-key "Strobel_1997" ebib-db #s(ebib--db-struct #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("Strobel_1997" (("publisher" . "{Springer New York}") ("journal" . "{Linux}") ("isbn" . "9781461218562") ("url" . "{http://dx.doi.org/10.1007/978-1-4612-1856-2_13}") ("doi" . "{10.1007/978-1-4612-1856-2_13}") ("pages" . "{347–384}") ("year" . "1997") ("title" . "{GNU Emacs}") ("author" . "{Strobel, Stefan and Elling, Volker}") ("=type=" . "Article") ("=key=" . "Strobel_1997")) ...)) nil nil nil nil nil #<buffer  1:test.bib> "Strobel_1997" nil nil nil "/home/magic/mgc/code/org/ebib/test.bib" (23633 43760 217328 777000) nil t)) 36 37 (ebib-key "Strobel_1997" ebib-db #s(ebib--db-struct #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("Strobel_1997" (("publisher" . "{Springer New York}") ("journal" . "{Linux}") ("isbn" . "9781461218562") ("url" . "{http://dx.doi.org/10.1007/978-1-4612-1856-2_13}") ("doi" . "{10.1007/978-1-4612-1856-2_13}") ("pages" . "{347–384}") ("year" . "1997") ("title" . "{GNU Emacs}") ("author" . "{Strobel, Stefan and Elling, Volker}") ("=type=" . "Article") ("=key=" . "Strobel_1997")) ...)) nil nil nil nil nil #<buffer  1:test.bib> "Strobel_1997" nil nil nil "/home/magic/mgc/code/org/ebib/test.bib" (23633 43760 217328 777000) nil t) ebib--xref nil) 37 43 (ebib-key "Strobel_1997" ebib-db #s(ebib--db-struct #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("Strobel_1997" (("publisher" . "{Springer New York}") ("journal" . "{Linux}") ("isbn" . "9781461218562") ("url" . "{http://dx.doi.org/10.1007/978-1-4612-1856-2_13}") ("doi" . "{10.1007/978-1-4612-1856-2_13}") ("pages" . "{347–384}") ("year" . "1997") ("title" . "{GNU Emacs}") ("author" . "{Strobel, Stefan and Elling, Volker}") ("=type=" . "Article") ("=key=" . "Strobel_1997")) ...)) nil nil nil nil nil #<buffer  1:test.bib> "Strobel_1997" nil nil nil "/home/magic/mgc/code/org/ebib/test.bib" (23633 43760 217328 777000) nil t)) 43 44 (ebib-key "Strobel_1997" ebib-db #s(ebib--db-struct #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("Strobel_1997" (("publisher" . "{Springer New York}") ("journal" . "{Linux}") ("isbn" . "9781461218562") ("url" . "{http://dx.doi.org/10.1007/978-1-4612-1856-2_13}") ("doi" . "{10.1007/978-1-4612-1856-2_13}") ("pages" . "{347–384}") ("year" . "1997") ("title" . "{GNU Emacs}") ("author" . "{Strobel, Stefan and Elling, Volker}") ("=type=" . "Article") ("=key=" . "Strobel_1997")) ...)) nil nil nil nil nil #<buffer  1:test.bib> "Strobel_1997" nil nil nil "/home/magic/mgc/code/org/ebib/test.bib" (23633 43760 217328 777000) nil t) ebib--xref nil) 44 53 (ebib-key "Strobel_1997" ebib-db #s(ebib--db-struct #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("Strobel_1997" (("publisher" . "{Springer New York}") ("journal" . "{Linux}") ("isbn" . "9781461218562") ("url" . "{http://dx.doi.org/10.1007/978-1-4612-1856-2_13}") ("doi" . "{10.1007/978-1-4612-1856-2_13}") ("pages" . "{347–384}") ("year" . "1997") ("title" . "{GNU Emacs}") ("author" . "{Strobel, Stefan and Elling, Volker}") ("=type=" . "Article") ("=key=" . "Strobel_1997")) ...)) nil nil nil nil nil #<buffer  1:test.bib> "Strobel_1997" nil nil nil "/home/magic/mgc/code/org/ebib/test.bib" (23633 43760 217328 777000) nil t))))
  ivy-call()
  ivy-read("Select entry: " (#("Strobel, Stefan and Elling, Volker (1997) «GNU Emacs»" 0 1 (ebib--xref nil ebib-db #s(ebib--db-struct #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("Strobel_1997" (("publisher" . "{Springer New York}") ("journal" . "{Linux}") ("isbn" . "9781461218562") ("url" . "{http://dx.doi.org/10.1007/978-1-4612-1856-2_13}") ("doi" . "{10.1007/978-1-4612-1856-2_13}") ("pages" . "{347–384}") ("year" . "1997") ("title" . "{GNU Emacs}") ("author" . "{Strobel, Stefan and Elling, Volker}") ("=type=" . "Article") ("=key=" . "Strobel_1997")) ...)) nil nil nil nil nil #<buffer  1:test.bib> "Strobel_1997" nil nil nil "/home/magic/mgc/code/org/ebib/test.bib" (23633 43760 217328 777000) nil t) ebib-key "Strobel_1997") 1 36 (ebib-db #s(ebib--db-struct #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("Strobel_1997" (("publisher" . "{Springer New York}") ("journal" . "{Linux}") ("isbn" . "9781461218562") ("url" . "{http://dx.doi.org/10.1007/978-1-4612-1856-2_13}") ("doi" . "{10.1007/978-1-4612-1856-2_13}") ("pages" . "{347–384}") ("year" . "1997") ("title" . "{GNU Emacs}") ("author" . "{Strobel, Stefan and Elling, Volker}") ("=type=" . "Article") ("=key=" . "Strobel_1997")) ...)) nil nil nil nil nil #<buffer  1:test.bib> "Strobel_1997" nil nil nil "/home/magic/mgc/code/org/ebib/test.bib" (23633 43760 217328 777000) nil t) ebib-key "Strobel_1997") 36 37 (ebib--xref nil ebib-db #s(ebib--db-struct #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("Strobel_1997" (("publisher" . "{Springer New York}") ("journal" . "{Linux}") ("isbn" . "9781461218562") ("url" . "{http://dx.doi.org/10.1007/978-1-4612-1856-2_13}") ("doi" . "{10.1007/978-1-4612-1856-2_13}") ("pages" . "{347–384}") ("year" . "1997") ("title" . "{GNU Emacs}") ("author" . "{Strobel, Stefan and Elling, Volker}") ("=type=" . "Article") ("=key=" . "Strobel_1997")) ...)) nil nil nil nil nil #<buffer  1:test.bib> "Strobel_1997" nil nil nil "/home/magic/mgc/code/org/ebib/test.bib" (23633 43760 217328 777000) nil t) ebib-key "Strobel_1997") 37 43 (ebib-db #s(ebib--db-struct #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("Strobel_1997" (("publisher" . "{Springer New York}") ("journal" . "{Linux}") ("isbn" . "9781461218562") ("url" . "{http://dx.doi.org/10.1007/978-1-4612-1856-2_13}") ("doi" . "{10.1007/978-1-4612-1856-2_13}") ("pages" . "{347–384}") ("year" . "1997") ("title" . "{GNU Emacs}") ("author" . "{Strobel, Stefan and Elling, Volker}") ("=type=" . "Article") ("=key=" . "Strobel_1997")) ...)) nil nil nil nil nil #<buffer  1:test.bib> "Strobel_1997" nil nil nil "/home/magic/mgc/code/org/ebib/test.bib" (23633 43760 217328 777000) nil t) ebib-key "Strobel_1997") 43 44 (ebib--xref nil ebib-db #s(ebib--db-struct #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("Strobel_1997" (("publisher" . "{Springer New York}") ("journal" . "{Linux}") ("isbn" . "9781461218562") ("url" . "{http://dx.doi.org/10.1007/978-1-4612-1856-2_13}") ("doi" . "{10.1007/978-1-4612-1856-2_13}") ("pages" . "{347–384}") ("year" . "1997") ("title" . "{GNU Emacs}") ("author" . "{Strobel, Stefan and Elling, Volker}") ("=type=" . "Article") ("=key=" . "Strobel_1997")) ...)) nil nil nil nil nil #<buffer  1:test.bib> "Strobel_1997" nil nil nil "/home/magic/mgc/code/org/ebib/test.bib" (23633 43760 217328 777000) nil t) ebib-key "Strobel_1997") 44 53 (ebib-db #s(ebib--db-struct #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("Strobel_1997" (("publisher" . "{Springer New York}") ("journal" . "{Linux}") ("isbn" . "9781461218562") ("url" . "{http://dx.doi.org/10.1007/978-1-4612-1856-2_13}") ("doi" . "{10.1007/978-1-4612-1856-2_13}") ("pages" . "{347–384}") ("year" . "1997") ("title" . "{GNU Emacs}") ("author" . "{Strobel, Stefan and Elling, Volker}") ("=type=" . "Article") ("=key=" . "Strobel_1997")) ...)) nil nil nil nil nil #<buffer  1:test.bib> "Strobel_1997" nil nil nil "/home/magic/mgc/code/org/ebib/test.bib" (23633 43760 217328 777000) nil t) ebib-key "Strobel_1997"))) :action #f(compiled-function (item) #<bytecode 0x22ca6a5>) :history ebib--citation-history :sort t)
  ebib-ivy-insert-citation()
  ebib-insert-citation()
  funcall-interactively(ebib-insert-citation)
  call-interactively(ebib-insert-citation nil nil)
  command-execute(ebib-insert-citation)
```

**Comment by joostkremers** [comment] 2019-01-31 13:36
Sorry, I noticed now that you put the full error in the subject line... I'm really surprised that you're getting this error, because before calling `with-ivy-window`, Ebib makes sure that `ivy` is installed and loaded. Perhaps you have an older version of the `ivy` package installed that doesn't have `with-ivy-window`?

What do you get when you do `M-: (featurep 'ivy)`?

**Comment by mgcyung** [comment] 2019-01-31 14:52
> Sorry, I noticed now that you put the full error in the subject line... I'm really surprised that you're getting this error, because before calling `with-ivy-window`, Ebib makes sure that `ivy` is installed and loaded. Perhaps you have an older version of the `ivy` package installed that doesn't have `with-ivy-window`?
>
> What do you get when you do `M-: (featurep 'ivy)`?

`M-: (featurep 'ivy)` returns `t`. ivy is installed by melpa and the
version is 20190126.2035. `with-ivy-window` exist and the help says
```
with-ivy-window is a Lisp macro in
‘~/mgc/config/emacs.d-26.1/elpa-26.1/ivy-20190126.2035/ivy.el’.

(with-ivy-window &rest BODY)

Execute BODY in the window from which ‘ivy-read’ was called.

```

**Comment by joostkremers** [comment] 2019-01-31 18:40
Actually, I realise now that the error is not saying that `with-ivy-window` is not defined. That would yield a `Symbol's function definition is void` error. There is something else that causes the error. But I have no idea what that could be...

Could you try and run Ebib uncompiled to see if that yields a better backtrace? Just move the file `ebib.elc` out of the way and restart Emacs.

Also, can you replicate the error with `emacs -Q`, loading just the packages ivy, parsebib and Ebib?

**Comment by joostkremers** [comment] 2019-01-31 19:13
I searched the ivy repo for similar issues and found one: https://github.com/abo-abo/swiper/issues/185. It seems that this error message can be caused by an incorrect byte compilation.

A recompilation of `ebib.el` should solve the issue. Or otherwise deleting Ebib, restarting Emacs and reinstalling Ebib.

Perhaps I should add a `require` statement to `ebib.el`, so that ivy is loaded when `ebib.el` is byte-compiled.

Let me know if recompiling / reinstalling solves the issue.

**Comment by mgcyung** [comment] 2019-02-01 00:54
> I searched the ivy repo for similar issues and found one: https://github.com/abo-abo/swiper/issues/185. It seems that this error message can be caused by an incorrect byte compilation.
>
> A recompilation of `ebib.el` should solve the issue. Or otherwise deleting Ebib, restarting Emacs and reinstalling Ebib.
>
> Perhaps I should add a `require` statement to `ebib.el`, so that ivy is loaded when `ebib.el` is byte-compiled.
>
> Let me know if recompiling / reinstalling solves the issue.

The error is gone after "ebib.elc" is removed. However, the same error
exists after deleting Ebib, restarting Emacs and reinstalling Ebib.

**Comment by joostkremers** [comment] 2019-02-01 22:20
> The error is gone after "ebib.elc" is removed. However, the same error 
exists after deleting Ebib, restarting Emacs and reinstalling Ebib.

I found a scenario in which this can happen. If Ebib is installed (compiled) before the ivy package is loaded, you'll get this error once you try to insert a citation.

I've pushed a fix for this to Melpa: Ebib now `require`s the ivy package if it's installed. That means it will also be loaded when Ebib is compiled, so the macro `with-ivy-window` is recognised correctly.

Once the update gets through to Melpa, please install it and let me know if you are still running into problems. Thanks for reporting the issue.

**Closed by joostkremers** 2019-02-01 22:20 UTC
Labels: Bug

**Comment by mgcyung** [comment] 2019-02-02 02:02
On Sat, 02 Feb 2019 06:20:02 +0800,
Joost Kremers wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> [2  <text/html; UTF-8 (quoted-printable)>]
>     The error is gone after "ebib.elc" is removed. However, the same error
>     exists after deleting Ebib, restarting Emacs and reinstalling Ebib.
>    
> I found a scenario in which this can happen. If Ebib is installed (compiled) before the ivy package is loaded, you'll get this error once you try to insert a citation.
> 
> I've pushed a fix for this to Melpa: Ebib now requires the ivy package if it's installed. That means it will also be loaded when Ebib is compiled, so the macro with-ivy-window is recognised correctly.
> 
> Once the update gets through to Melpa, please install it and let me know if you are still running into problems. Thanks for reporting the issue.
> 
> ―
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 
> 

The commit fix the problem. Thanks.

**Comment by joostkremers** [comment] 2019-02-02 21:14
Great! Thanks for letting me know.
