### ISSUE TITLE
lisp error when adding an entry

### ISSUE THREAD

**Issue by spmima** [joostkremers/ebib#183] opened 2020-09-29 11:15 UTC
When I try to add an entry in ebib, I get lisp error saying "Lisp nesting exceeds 'max-lisp-eval-depth'. The error appears, not on first line (article-book-InBook and so on) but on the second issue, "author". 

I tried to increase eval-depth in init-file: 
 
(setq max-lisp-eval-depth 1300)
(setq max-specpdl-size 13000)
but it did not help. 

My emacs is 28.

**Comment by joostkremers** [comment] 2020-09-29 12:46
> When I try to add an entry in ebib, I get lisp error saying "Lisp nesting exceeds 'max-lisp-eval-depth'. The error appears, not on first line (article-book-InBook and so on) but on the second issue, "author".

Do you mean that when you press `a` in the index buffer (the top one) to add an entry, the entry buffer (the lower one) shows just the `type` and `author` fields, and then nothing?

> I tried to increase eval-depth in init-file:

It makes sense that that doesn't help. The error you report is usually an indication that the program gets stuck in infinite recursion.

Are you able to provide a backtrace of the error? That might be helpful in figuring out what's going on. I'm running Emacs 27 and everything works fine here. I'd have to install Emacs 28 to debug this, which I won't have time for until perhaps this weekend.

**Comment by spmima** [comment] 2020-09-29 13:47
Yes, after pushing "a" in the index window, the entry buffer opens but when I try to write to the second field on it, (in my case "author", I cannot do it -- and then I get the lisp error code. I am sorry but I do not know how to produce a backtrace. Here is the logfile:
------------ start ----------------------
Loading /home/USER/.emacs.d/emacs-custom.el (source)...done
For information about GNU Emacs and the GNU system, type C-h C-a.
Mark set
Making completion list...
Quit
37 entries, 0 @Strings and no @Preamble found in file.
progn: Lisp nesting exceeds ‘max-lisp-eval-depth’
Making completion list... [3 times]
---- end ----


ebib is in many ways the most rational way to work with emacs / markdown system, and it is very much possible
that the problem lies in my init.el file.

**Comment by joostkremers** [comment] 2020-09-29 18:40
>  I am sorry but I do not know how to produce a backtrace.

Do `M-x toggle-debug-on-error RET` and then trigger the error. A buffer called `*backtrace*` should pop up. If you could copy the contents of that buffer and paste it here, that would be great.

Then you can do `M-x toggle-debug-on-error` again, so you won't see the backtrace buffer every time an error occurs...

**Comment by spmima** [comment] 2020-09-30 07:08
[Backtrace.txt](https://github.com/joostkremers/ebib/files/5303658/Backtrace.txt)

**Comment by spmima** [comment] 2020-09-30 07:08
Hope this helps.

**Comment by joostkremers** [comment] 2020-09-30 10:19
Well, at least it tells me where the error occurs exactly. As a workaround, you can unset the option `ebib-edit-author/editor-without-completion`, then you can edit the Author and Editor fields normally, though without completion on author names.

I suspect a bug was introduced into Emacs 28 recently that made this code stop working. It could be that the bug will be found soon and resolved, but if not, I'll have to look at it more closely and see if I can come up with a simpler recipe to present to the Emacs devs.

**Comment by spmima** [comment] 2020-09-30 11:10
Thank you ! Turning off the ebib-edit-author helped, but now I get the same error on publisher. I check if I can turn even that off

**Comment by spmima** [comment] 2020-09-30 11:41
here is a backtrace from the other error. 
[Backtrace2.txt](https://github.com/joostkremers/ebib/files/5305152/Backtrace2.txt)

**Comment by joostkremers** [comment] 2020-09-30 19:49
That backtrace is rather short, but I suspect that one of the `seq-*` functions is broken in Emacs 28. That's really something that should be looked into.

Unfortunately, I can't offer a quick solution to this problem. Some fields, when edited, trigger completion no matter what. That should really be user-configurable, but currently it is not.

What you could do is edit the following line in `ebib.el`:

https://github.com/joostkremers/ebib/blob/master/ebib.el#L3861

And empty the list, i.e., change the part that says:

    '("journal" "journaltitle" "publisher" "organization")

to:

    '()

Then recompile and reload the file with `M-x emacs-lisp-byte-compile-and-load RET`. That should allow you to edit the relevant fields without completion.

But I would first try upgrading Emacs. Emacs 28 is the current development version, so the problem that you encounter may already be fixed in a more recent update.

**Comment by spmima** [comment] 2020-10-01 07:20
Thank you so much for your help! I re-installed emacs (28.0,50, date 28.9.2020), commented out org-ref section in my init.el and now the ebib is working without problem. Probably it was a bug in my previous snapshot version of emacs, as you said.

**Comment by joostkremers** [comment] 2020-10-01 07:25
Any particular reason you commented out the org-ref section in your init.el? Not that the problem is related to your org-ref setup...

**Comment by spmima** [comment] 2020-10-01 13:35
I commented it out because I thought that org-ref settings might hinder or interfere somehow ebib. It really did not have anything to do with the problem. I just repeated the process with my other computer (which had the same issue). I deleted and installed emacs again. The version number is the same, but the date differs -- and ebib seems to be working correctly now.

**Comment by joostkremers** [comment] 2020-10-01 13:55
Glad it's working again. 😌 I don't think`org-ref` settings would interfere with Ebib, it should be safe to use both. Only if you modify your `.bib` files outside Ebib, Ebib won't notice the change. You'd have to reload the file (which you can do with `r`).

That said, I don't use `org-ref`, so I can't be entirely sure.

**Closed** 2020-10-01 13:56 UTC
Labels: Possible bug, Upstream bug
